@startuml

skinparam packageStyle rectangle
hide circle
scale 1.2

title 掲示板型メモ帳 依存関係

package DB共通処理 {
  object PDO {
  }
  object Db {
  }
}
package モデル {
  object ArticleModel {
  }
  object TagModel {
  }
  object ArticleRepository {
  }
  object TagRepository {
  }
}
package プレゼンテーション/IO {
  object Page {
  }
  object Html {
  }
  object Form {
  }
  object ArticleDao {
  }
  object TagDao {
  }
}

object AppMain {
}
object Response {
}
object Session {
}

AppMain -d-> Page
Page --> Html
Page --> Form
Page --> ArticleDao
Page --> TagDao
Page -l-> ArticleModel
Page -l-> TagModel
Page -u-> Session
Page -u-> Response

Db --> PDO
ArticleDao --> Db
TagDao --> Db
ArticleRepository <|-- ArticleDao
TagRepository <|-- TagDao
Html -r-> Form
Html -u-|> Response
ArticleModel --> ArticleRepository
TagModel --> TagRepository
AppMain -l-> Response

@enduml
