@startuml

skinparam packageStyle rectangle
hide circle
scale 1.2

title 掲示板型メモ帳 依存関係

package ドメイン {
  object ArticleModel {
  }
  object TagModel {
  }
  object ArticleRepository {
  }
  object TagRepository {
  }
}
package アプリケーションサービス {
  object ArticleService {
  }
}

package IO {
package インフラ {
  object Db {
  }
  object ArticleDao {
  }
  object TagDao {
  }
  object Session {
  }
  object Response {
  }
}
package コントローラー {
  object Page {
  }
}
package プレゼンテーション {
  object Html {
  }
  object Form {
  }
}
}
object AppMain {
}

AppMain --> Page
Page -l-> Html
Page --> Form
Page --> ArticleDao
Page --> TagDao
ArticleService --> ArticleModel
ArticleService --> TagModel
Page --> ArticleService
Page --> Session
Page --> Response
Page --> Db

ArticleService --> ArticleRepository
ArticleService --> TagRepository

ArticleDao --> Db
TagDao --> Db
ArticleRepository <|-- ArticleDao
TagRepository <|-- TagDao
Html --> Form
Html --|> Response
ArticleModel --> ArticleRepository
TagModel --> TagRepository
AppMain --> Response

@enduml
